# Generated by Django 3.2.25 on 2024-03-18 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is42account', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('profile_picture', models.CharField(blank=True, default='avatar.jpg', max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('correction_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
