# Generated by Django 5.0.1 on 2024-03-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_notifications_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='JankenGameCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_creation', to='auth_app.profile')),
            ],
            options={
                'verbose_name': 'Janken Game Creation',
                'verbose_name_plural': 'Janken Game Creations',
            },
        ),
        migrations.CreateModel(
            name='JankenGameInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_choice', models.IntegerField(default=0)),
                ('opponent_choice', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth_app.profile')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='auth_app.profile')),
            ],
        ),
    ]
