# Generated by Django 5.0.1 on 2024-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_jankengamecreation_jankengameinprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='creator_choice',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='opponent_choice',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
