# Generated by Django 5.0.1 on 2024-03-19 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20231222_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is42account', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('profile_picture', models.CharField(blank=True, default='avatar.jpg', max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('correction_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
