# Generated by Django 5.0.1 on 2024-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_jankengameinprogress_creator_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengamecreation',
            name='isWaiting',
            field=models.BooleanField(default=False),
        ),
    ]
