# Generated by Django 3.2.25 on 2024-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20231222_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='files/covers/dune.jpg', upload_to='./files/covers'),
        ),
    ]
