# Generated by Django 3.2.25 on 2024-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='files/covers/dune.jpg', null=True, upload_to='./files/covers'),
        ),
    ]
