# Generated by Django 5.0.1 on 2024-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_jankengamecreation_iswaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='game_finished',
            field=models.BooleanField(default=False),
        ),
    ]
