# Generated by Django 5.0.1 on 2024-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_jankengameinprogress_game_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
