# Generated by Django 3.2.25 on 2024-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='truc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
