# Generated by Django 5.0.1 on 2024-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_profile_online_alter_friendship_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='default@default.default', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='No Nickname Yet', max_length=100),
        ),
    ]
