# Generated by Django 5.0.1 on 2024-03-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_rename_to_delete_jankengameinprogress_to_delete_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jankengameinprogress',
            old_name='to_delete_creator',
            new_name='to_delete',
        ),
        migrations.RemoveField(
            model_name='jankengameinprogress',
            name='to_delete_opponent',
        ),
    ]
