# Generated by Django 5.0.1 on 2024-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_rename_to_delete_creator_jankengameinprogress_to_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
