# Generated by Django 5.0.1 on 2024-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_jankengameinprogress_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='loser',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
