# Generated by Django 5.0.1 on 2024-03-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_jankengameinprogress_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='winner',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
