# Generated by Django 5.0.1 on 2024-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_jankengameinprogress_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jankengameinprogress',
            name='first_input_nickname',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='jankengameinprogress',
            name='first_input_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
