# Generated by Django 5.0.1 on 2024-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_jankengameinprogress_first_input_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jankengameinprogress',
            old_name='to_delete',
            new_name='to_delete_creator',
        ),
        migrations.AddField(
            model_name='jankengameinprogress',
            name='to_delete_opponent',
            field=models.BooleanField(default=False),
        ),
    ]
