# Generated by Django 5.0.1 on 2024-03-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_rename_to_delete_jankengameinprogress_to_delete_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedJankenGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_choice', models.CharField(max_length=100)),
                ('opponent_choice', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('completion_time', models.DateTimeField()),
                ('loser', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JankenHistoryOpponent', to='auth_app.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JankenHistoryOwner', to='auth_app.profile')),
            ],
        ),
    ]
