# Generated by Django 5.0.1 on 2024-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_finishedjankengames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedjankengames',
            options={'verbose_name': 'Finished Janken Game', 'verbose_name_plural': 'Finished Janken Games'},
        ),
        migrations.AlterModelOptions(
            name='jankengameinprogress',
            options={'verbose_name': 'Janken Game In Progress', 'verbose_name_plural': 'Janken Games In Progress'},
        ),
    ]
