# Generated by Django 5.0.1 on 2024-03-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_finishedjankengames_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedPongGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('completion_time', models.DateTimeField()),
                ('loser', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PongHistoryOpponent', to='auth_app.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PongHistoryOwner', to='auth_app.profile')),
            ],
            options={
                'verbose_name': 'Finished Pong Game',
                'verbose_name_plural': 'Finished Pong Games',
            },
        ),
    ]
