# Generated by Django 5.0.1 on 2024-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_finishedponggames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedponggames',
            name='loser',
        ),
        migrations.AddField(
            model_name='finishedponggames',
            name='completion_day',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedponggames',
            name='game_type',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedponggames',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finishedponggames',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finishedponggames',
            name='completion_time',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='finishedponggames',
            name='opponent',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='finishedponggames',
            name='result',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='finishedponggames',
            name='winner',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
