# Generated by Django 5.0.1 on 2024-03-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_remove_finishedponggames_loser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jankengamecreation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='jankengameinprogress',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='jankengameinprogress',
            name='opponent',
        ),
        migrations.DeleteModel(
            name='FinishedJankenGames',
        ),
        migrations.DeleteModel(
            name='JankenGameCreation',
        ),
        migrations.DeleteModel(
            name='JankenGameInProgress',
        ),
    ]
