# Generated by Django 5.0.1 on 2024-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_remove_finishedponggames_loser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
