# Generated by Django 3.2.23 on 2023-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(default='your@email.com', max_length=100, unique=True)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
