version: '3'

services:
  frontend:
    build:
      context: ./PONG/frontend/src
      dockerfile: Dockerfile
    volumes:
      - ./PONG/frontend/src:/app
    networks:
      - front
    depends_on:
      - frontend_db

  nginx:
    build:
      context: ./PONG/frontend/nginx
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - frontend
    networks:
      - front

  frontend_db:
    image: postgres:16-bookworm
    volumes:
      - front_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: frontend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - front

  authentification:
    build:
      context: ./PONG/authentification/src
      dockerfile: Dockerfile
    volumes:
      - ./PONG/authentification/src:/app
    ports:
      - "8002:8000"
    networks:
      - auth
    depends_on:
      - authentification_db


  authentification_db:
    image: postgres:16-bookworm
    volumes:
      - auth_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: authentification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    networks:
      - auth

volumes:
  front_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vburton/data/transcendence_data/front_db'
  auth_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vburton/data/transcendence_data/auth_db'


networks:
  front:
    driver: bridge
  auth:
    driver: bridge
