version: '3'

services:
  frontend:
    build:
      context: ./PONG/frontend/src
      dockerfile: Dockerfile
    networks:
      - front
    depends_on:
      - frontend_db

  nginx:
    build:
      context: ./PONG/frontend/nginx
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - frontend
    networks:
      - front

  frontend_db:
    image: postgres:latest
    volumes:
      - front_postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: frontend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - front

  authentification:
    build:
      context: ./PONG/authentification/src
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    networks:
      - auth
    depends_on:
      - authentification_db


  authentification_db:
    image: postgres:latest
    volumes:
      - auth_postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: authentification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - auth

volumes:
  front_postgres_db:
  auth_postgres_db:


networks:
  front:
    driver: bridge
  auth:
    driver: bridge
