version: '3'

services:
  frontend:
    build:
      context: ./PONG/frontend/src
      dockerfile: Dockerfile
    volumes:
      - ./PONG/frontend/src:/app
    networks:
      - front
    depends_on:
      - frontend_db

  nginx:
    build:
      context: ./PONG/frontend/nginx
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - frontend
    networks:
      - front

  frontend_db:
    image: postgres:16-bookworm
    volumes:
      - front_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: frontend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - front

  authentification:
    build:
      context: ./PONG/authentification/src
      dockerfile: Dockerfile
    volumes:
      - ./PONG/authentification/src:/app
    ports:
      - "8002:8000"
    networks:
      - auth
    depends_on:
      - authentification_db

  authentification_db:
    image: postgres:16-bookworm
    volumes:
      - auth_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: authentification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - auth
    ports:
      - 5432

  game:
    build:
      context: ./PONG/game
      dockerfile: Dockerfile
    volumes:
      - ./PONG/game:/app
    ports:
      - "8003:8000"
    networks:
      - game
    depends_on:
      - game_db

  game_db:
    image: postgres:16-bookworm
    volumes:
      - game_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: game_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - game

  bot:
    build:
      context: ./PONG/bot
      dockerfile: Dockerfile
    volumes:
      - ./PONG/bot:/app
    ports:
      - "8004:8000"
    networks:
      - bot
    depends_on:
      - bot_db

  bot_db:
    image: postgres:16-bookworm
    volumes:
      - bot_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    networks:
      - bot

volumes:
  front_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $FRNT_DB_VOL

  auth_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $AUTH_DB_VOL

  game_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $GAME_DB_VOL

  bot_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $BOT_DB_VOL

networks:
  front:
    driver: bridge
  auth:
    driver: bridge
  game:
    driver: bridge
  bot:
    driver: bridge
