# Generated by Django 5.0.1 on 2024-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janken_app', '0002_alter_finishedjankengames_loser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedjankengames',
            name='loser',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='finishedjankengames',
            name='opponent',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='finishedjankengames',
            name='owner',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='finishedjankengames',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengamecreation',
            name='creator',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='creator',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='first_input_nickname',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='loser',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='opponent',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jankengameinprogress',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
    ]
