{
 "title": "Big Overview 2",
 "time": { "from": "2024-01-31T23:46:45.963Z", "to": "2024-02-02T07:46:45.963Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"front\"}[1m])",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Authentification",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"auth\"}[1m])",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Node Exporter",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"nodeExporter\"}[1m])",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Prometheus",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"auth\"}[1m])",
       "legendFormat": "__auto"
      },
      {}
     ]
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Front",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"front\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Front 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Front 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Front 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Authentification 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Authentification 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Authentification 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "front",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"front\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "front",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"auth\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Front",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"front\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"front\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Front",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"auth\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"auth\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Auth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(django_db_query_duration_seconds_sum[5m]) / rate(django_db_query_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}