# Generated by Django 5.0.1 on 2024-01-19 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(choices=[('waiting', 'Waiting for player...'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], max_length=8)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player1_x', models.IntegerField(default=0)),
                ('player2_x', models.IntegerField(default=0)),
                ('ball_x', models.IntegerField(default=0)),
                ('ball_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
                ('total_rounds', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='ball_x',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='ball_y',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='game_status',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player1_x',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player2_x',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('local', 'Local'), ('remote', 'Remote'), ('ai', 'AI'), ('tournament', 'TournamentSession')], max_length=10),
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote'), ('ai', 'AI'), ('tournament', 'TournamentSession')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong_game.gamestate'),
        ),
        migrations.CreateModel(
            name='TournamentSession',
            fields=[
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=64)),
                ('current_number_of_players', models.IntegerField(default=0)),
                ('max_number_of_players', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('games', models.ManyToManyField(to='pong_game.gameresult')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong_game.tournamentsession')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
