# Generated by Django 5.0.1 on 2024-03-28 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedPongGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('game_type', models.CharField(default='None', max_length=100)),
                ('opponent', models.IntegerField(default=-1)),
                ('player_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=-1)),
                ('result', models.CharField(default='None', max_length=100)),
                ('completion_day', models.CharField(default='None', max_length=100)),
                ('completion_time', models.CharField(default='None', max_length=100)),
            ],
            options={
                'verbose_name': 'Finished Pong Game',
                'verbose_name_plural': 'Finished Pong Games',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
