# Generated by Django 5.0.1 on 2024-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedPongGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('game_type', models.CharField(default='None', max_length=100)),
                ('opponent', models.CharField(default='Player 2', max_length=100)),
                ('player_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('winner', models.CharField(default='Player 2', max_length=100)),
                ('result', models.CharField(default='None', max_length=100)),
                ('completion_day', models.CharField(default='None', max_length=100)),
                ('completion_time', models.CharField(default='None', max_length=100)),
                ('player1', models.CharField(default='', max_length=100)),
                ('tourney_game', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Finished Pong Game',
                'verbose_name_plural': 'Finished Pong Games',
            },
        ),
    ]
