# Generated by Django 5.0.1 on 2024-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_alter_finishedponggames_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedponggames',
            name='winner',
            field=models.CharField(default='Player 2', max_length=100),
        ),
    ]
