# Generated by Django 5.0.1 on 2024-04-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_tournament_tx_delete_gamemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tournament',
        ),
    ]
