# Generated by Django 5.0.1 on 2024-01-24 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("remote", "Remote"),
                            ("ai", "AI"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for player..."),
                            (STATUS_ACTIVE, "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        max_length=32,
                    ),
                ),
                ("score1", models.IntegerField(default=0)),
                ("score2", models.IntegerField(default=0)),
                ("player1_x", models.IntegerField(default=0)),
                ("player1_y", models.IntegerField(default=0)),
                ("player1_w", models.IntegerField(default=0)),
                ("player1_h", models.IntegerField(default=0)),
                ("player1_dx", models.IntegerField(default=0)),
                ("player2_x", models.IntegerField(default=0)),
                ("player2_y", models.IntegerField(default=0)),
                ("player2_w", models.IntegerField(default=0)),
                ("player2_h", models.IntegerField(default=0)),
                ("player2_dx", models.IntegerField(default=0)),
                ("ball_x", models.IntegerField(default=0)),
                ("ball_y", models.IntegerField(default=0)),
                ("ball_w", models.IntegerField(default=0)),
                ("ball_h", models.IntegerField(default=0)),
                ("ball_dx", models.IntegerField(default=0)),
                ("ball_dy", models.IntegerField(default=0)),
                (
                    "player1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_sessions_as_player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_sessions_as_player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
