# Generated by Django 5.0.1 on 2024-01-27 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_dx',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_dy',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_h',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_w',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_x',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='ball_y',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_dx',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_h',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_w',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_x',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_y',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_dx',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_h',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_w',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_x',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_y',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
