import math

# BOARD
BOARD_WIDTH = 480
BOARD_HEIGHT = 650
BOARD_MARGIN = 16
BOARD_CORRIDOR = 2 * BOARD_MARGIN + 10

# INPUTS
INPUT_LEFT = 0
INPUT_RIGHT = 1
INPUT_SPACE = 2
INPUT_NEUTRAL = 3
INPUT_QUIT = 4

INPUTS = [INPUT_LEFT, INPUT_RIGHT, INPUT_SPACE, INPUT_NEUTRAL, INPUT_QUIT]

# STATUSES
STATUS_BEGIN = 0
STATUS_ACTIVE = 1
STATUS_ENDED_1 = 2
STATUS_ENDED_2 = 3
STATUS_PAUSED = 4
STATUS_QUIT = 5
STATUS_SCORE = 6
STATUS_WAITING = 7

# GAME TYPES
TYPE_REMOTE = 0
TYPE_LOCAL = 1
TYPE_AI = 2

# PLAYERS' IDS
ID_PLAYER1 = 0
ID_PLAYER2 = 1

# BALL
BALL_SIDE = 16
BALL_SPEED_MIN = (BOARD_HEIGHT / 2) - BOARD_MARGIN
BALL_SPEED_MAX = BALL_SPEED_MIN * 2.0
BALL_MAX_ANGLE = math.pi / 6

# PADDLE
PADDLE_WIDTH = 64
PADDLE_SPEED = BOARD_WIDTH - (2 * BOARD_CORRIDOR)

POINTS_TO_WIN = 1
